# When version.txt is pushed, the commit body is used as release text.
name: ReleaseOnCommit

env:
  NAME: image-resize
  VERSION: "0.0.1"

on:
  push:
    branches:
      - main
      - master
    paths:
      - "version.txt"

jobs:
  build:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
      - name: Set variables
        run: |
          VER=$(cat version.txt | tr -d '\n')
          echo "VERSION=$VER" >> $GITHUB_ENV
          git log --format=%B -n 1 HEAD | tail -n +3 > body.md

      - name: Persist Commit
        run: |
          go version
          timedatectl
          echo $GITHUB_SHA > commit.txt
      - name: Build Linux
        run: env GOOS=linux GOARCH=amd64 go build -o ${NAME}-linux
      - name: UPX Linux
        uses: crazy-max/ghaction-upx@v1.3.3
        with:
          file: ${{env.NAME}}-linux

      - name: Build Linux arm
        # GOARM=6 (Raspberry Pi A, A+, B, B+, Zero) GOARM=7 (Raspberry Pi 2, 3)
        run: env GOARM=6 GOOS=linux GOARCH=arm go build -o ${NAME}-linux-arm
      - name: UPX Linux arm
        uses: crazy-max/ghaction-upx@v1.3.3
        with:
          file: ${{env.NAME}}-linux-arm

      - name: Build macOS amd64
        run: env GOOS=darwin GOARCH=amd64 go build -o ${NAME}-macos
      - name: UPX macOS amd64
        uses: crazy-max/ghaction-upx@v1.3.3
        with:
          file: ${{ env.NAME }}-macos

      - name: Build macOS arm64
        run: env GOOS=darwin GOARCH=arm64 go build -o ${NAME}-macos-arm
      - name: UPX macOS arm64
        uses: crazy-max/ghaction-upx@v1.3.3
        with:
          file: ${{ env.NAME }}-macos-arm

      - name: Build Windows
        run: env GOOS=windows GOARCH=amd64 go build -o ${NAME}-windows.exe
      - name: UPX Windows
        uses: crazy-max/ghaction-upx@v1.3.3
        with:
          file: ${{ env.NAME }}-windows.exe

      # https://github.com/ncipollo/release-action
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.NAME }}-*"
          tag: v${{ env.VERSION }}
          name: v${{ env.VERSION }}
          bodyFile: "body.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
